### ISSUE TITLE
How to re-run a main using cascal without hitting JMX issues

### ISSUE THREAD

**Issue by jstrachan** [shorrockin/cascal#20]
When running tests and sample programs in sbt (simple-build-tool) I get the following exception despite calling close and clear on the SessionPool

Is there a way we can make the CascalStatistics deal with this exception silently? Or some way to close down the pool which results in this mbean being deleted?

Caused by: javax.management.InstanceAlreadyExistsException: com.shorrockin.cascal:name=CascalStatistics
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:453)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.internal_addObject(DefaultMBeanServerInterceptor.java:1484)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:963)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:917)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:312)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:482)
        at com.shorrockin.cascal.jmx.CascalStatistics$.<init>(CascalStatistics.scala:15)
        at com.shorrockin.cascal.jmx.CascalStatistics$.<clinit>(CascalStatistics.scala)
        at com.shorrockin.cascal.session.SessionPool.<init>(SessionPool.scala:20)
        at com.shorrockin.cascal.session.SessionPool.<init>(SessionPool.scala:17)

**Comment by shorrockin** [comment]
Sure - looks like the mbean needs to be unregistered. Let me take a peek into that for you. 

With that said - I'm interested to see if you can manage to get Cassandra working within SBT. I originally attempted to migration (http://github.com/shorrockin/cascal/issues/closed#issue/5) and ran into a few issues. Cassandra did not remove its mbeans (I suppose I could remove it for them when I remove the Cascal MBeans) and I also had issues related to running out of permgen as SBT was not forking the test process. However I'd be interested in attempting to get this working again - so let me know what type of progress you make on it after I resolve the core Cascal JMX issues.

**Comment by jstrachan** [comment]
Ah good point. I guess I can raise issues against Cassandra if I hit its JMX issues too.

BTW I hit the permgen space issue now and again too (though tend to use a huge value in my sbt executable as a workaround).

I should raise an issue against sbt to allow things to be forked too :)

**Comment by jstrachan** [comment]
Ah! Looks like you just add this to your sbt build file...
  override def fork = forkRun

and it works fine!

http://code.google.com/p/simple-build-tool/wiki/Forking

**Comment by shorrockin** [comment]
ok - this one should be addressed - the mbean now has a check to see if it's already registered and unregisters prior to re-registering. 

Available in maven as 1.2-SNAPSHOT.

http://github.com/shorrockin/cascal/commit/cb39c30ced972a41aa8aa3678854cfc11478cc30.

**Comment by shorrockin** [comment]
Wow - Good find on the forking - That's (great) news to me as I can largely do away with Maven now.
